// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/stannisl/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalyticsRepository creates a new instance of MockAnalyticsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyticsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalyticsRepository is an autogenerated mock type for the AnalyticsRepository type
type MockAnalyticsRepository struct {
	mock.Mock
}

type MockAnalyticsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepository_Expecter {
	return &MockAnalyticsRepository_Expecter{mock: &_m.Mock}
}

// AddAnalytics provides a mock function for the type MockAnalyticsRepository
func (_mock *MockAnalyticsRepository) AddAnalytics(ctx context.Context, redirectModel domain.UrlAnalyticsModel) error {
	ret := _mock.Called(ctx, redirectModel)

	if len(ret) == 0 {
		panic("no return value specified for AddAnalytics")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UrlAnalyticsModel) error); ok {
		r0 = returnFunc(ctx, redirectModel)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAnalyticsRepository_AddAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAnalytics'
type MockAnalyticsRepository_AddAnalytics_Call struct {
	*mock.Call
}

// AddAnalytics is a helper method to define mock.On call
//   - ctx context.Context
//   - redirectModel domain.UrlAnalyticsModel
func (_e *MockAnalyticsRepository_Expecter) AddAnalytics(ctx interface{}, redirectModel interface{}) *MockAnalyticsRepository_AddAnalytics_Call {
	return &MockAnalyticsRepository_AddAnalytics_Call{Call: _e.mock.On("AddAnalytics", ctx, redirectModel)}
}

func (_c *MockAnalyticsRepository_AddAnalytics_Call) Run(run func(ctx context.Context, redirectModel domain.UrlAnalyticsModel)) *MockAnalyticsRepository_AddAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UrlAnalyticsModel
		if args[1] != nil {
			arg1 = args[1].(domain.UrlAnalyticsModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsRepository_AddAnalytics_Call) Return(err error) *MockAnalyticsRepository_AddAnalytics_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAnalyticsRepository_AddAnalytics_Call) RunAndReturn(run func(ctx context.Context, redirectModel domain.UrlAnalyticsModel) error) *MockAnalyticsRepository_AddAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummary provides a mock function for the type MockAnalyticsRepository
func (_mock *MockAnalyticsRepository) GetSummary(ctx context.Context, urlID int) (*domain.AnalyticsSummary, error) {
	ret := _mock.Called(ctx, urlID)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 *domain.AnalyticsSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*domain.AnalyticsSummary, error)); ok {
		return returnFunc(ctx, urlID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *domain.AnalyticsSummary); ok {
		r0 = returnFunc(ctx, urlID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AnalyticsSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, urlID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAnalyticsRepository_GetSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummary'
type MockAnalyticsRepository_GetSummary_Call struct {
	*mock.Call
}

// GetSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - urlID int
func (_e *MockAnalyticsRepository_Expecter) GetSummary(ctx interface{}, urlID interface{}) *MockAnalyticsRepository_GetSummary_Call {
	return &MockAnalyticsRepository_GetSummary_Call{Call: _e.mock.On("GetSummary", ctx, urlID)}
}

func (_c *MockAnalyticsRepository_GetSummary_Call) Run(run func(ctx context.Context, urlID int)) *MockAnalyticsRepository_GetSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAnalyticsRepository_GetSummary_Call) Return(analyticsSummary *domain.AnalyticsSummary, err error) *MockAnalyticsRepository_GetSummary_Call {
	_c.Call.Return(analyticsSummary, err)
	return _c
}

func (_c *MockAnalyticsRepository_GetSummary_Call) RunAndReturn(run func(ctx context.Context, urlID int) (*domain.AnalyticsSummary, error)) *MockAnalyticsRepository_GetSummary_Call {
	_c.Call.Return(run)
	return _c
}
