// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/stannisl/url-shortener/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUrlRepository creates a new instance of MockUrlRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUrlRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUrlRepository {
	mock := &MockUrlRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUrlRepository is an autogenerated mock type for the UrlRepository type
type MockUrlRepository struct {
	mock.Mock
}

type MockUrlRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUrlRepository) EXPECT() *MockUrlRepository_Expecter {
	return &MockUrlRepository_Expecter{mock: &_m.Mock}
}

// CreateShortUrl provides a mock function for the type MockUrlRepository
func (_mock *MockUrlRepository) CreateShortUrl(ctx context.Context, originUrl string) (*domain.ShortenUrlModel, error) {
	ret := _mock.Called(ctx, originUrl)

	if len(ret) == 0 {
		panic("no return value specified for CreateShortUrl")
	}

	var r0 *domain.ShortenUrlModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.ShortenUrlModel, error)); ok {
		return returnFunc(ctx, originUrl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.ShortenUrlModel); ok {
		r0 = returnFunc(ctx, originUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ShortenUrlModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, originUrl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUrlRepository_CreateShortUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShortUrl'
type MockUrlRepository_CreateShortUrl_Call struct {
	*mock.Call
}

// CreateShortUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - originUrl string
func (_e *MockUrlRepository_Expecter) CreateShortUrl(ctx interface{}, originUrl interface{}) *MockUrlRepository_CreateShortUrl_Call {
	return &MockUrlRepository_CreateShortUrl_Call{Call: _e.mock.On("CreateShortUrl", ctx, originUrl)}
}

func (_c *MockUrlRepository_CreateShortUrl_Call) Run(run func(ctx context.Context, originUrl string)) *MockUrlRepository_CreateShortUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUrlRepository_CreateShortUrl_Call) Return(shortenUrlModel *domain.ShortenUrlModel, err error) *MockUrlRepository_CreateShortUrl_Call {
	_c.Call.Return(shortenUrlModel, err)
	return _c
}

func (_c *MockUrlRepository_CreateShortUrl_Call) RunAndReturn(run func(ctx context.Context, originUrl string) (*domain.ShortenUrlModel, error)) *MockUrlRepository_CreateShortUrl_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginUrl provides a mock function for the type MockUrlRepository
func (_mock *MockUrlRepository) GetOriginUrl(ctx context.Context, shortUrl string) (*domain.ShortenUrlModel, error) {
	ret := _mock.Called(ctx, shortUrl)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginUrl")
	}

	var r0 *domain.ShortenUrlModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.ShortenUrlModel, error)); ok {
		return returnFunc(ctx, shortUrl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.ShortenUrlModel); ok {
		r0 = returnFunc(ctx, shortUrl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ShortenUrlModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shortUrl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUrlRepository_GetOriginUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginUrl'
type MockUrlRepository_GetOriginUrl_Call struct {
	*mock.Call
}

// GetOriginUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - shortUrl string
func (_e *MockUrlRepository_Expecter) GetOriginUrl(ctx interface{}, shortUrl interface{}) *MockUrlRepository_GetOriginUrl_Call {
	return &MockUrlRepository_GetOriginUrl_Call{Call: _e.mock.On("GetOriginUrl", ctx, shortUrl)}
}

func (_c *MockUrlRepository_GetOriginUrl_Call) Run(run func(ctx context.Context, shortUrl string)) *MockUrlRepository_GetOriginUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUrlRepository_GetOriginUrl_Call) Return(shortenUrlModel *domain.ShortenUrlModel, err error) *MockUrlRepository_GetOriginUrl_Call {
	_c.Call.Return(shortenUrlModel, err)
	return _c
}

func (_c *MockUrlRepository_GetOriginUrl_Call) RunAndReturn(run func(ctx context.Context, shortUrl string) (*domain.ShortenUrlModel, error)) *MockUrlRepository_GetOriginUrl_Call {
	_c.Call.Return(run)
	return _c
}
